### ISSUE TITLE
defaultType is not used when passing a stream or buffer

### ISSUE THREAD

**Issue by pluma** [strikeentco/mime-kind#1]
The handling for `defaultType` only kicks in when passing in a filename.

Downstream libraries like [form-data](https://github.com/form-data/form-data) rely on `mime-kind` always returning an object and thus blow up when passing in a buffer or stream that can not be guessed.

The obvious fix would be to not return immediately but instead check if the handlers return something and fall back to the default value otherwise.

I can provide a PR if you don't have the time to address this yourself.

**Comment by strikeentco** [comment]
Hello!

This definitely a bug, I'll fix it asap (today or tomorrow).

Thanks for your report.

**Comment by strikeentco** [comment]
![01-jared-boom-done](https://cloud.githubusercontent.com/assets/2401029/26633763/200dba80-461d-11e7-9080-a3f822c1f456.gif)

**Comment by pluma** [comment]
Awesome! Thanks for the quick follow-up. :tada:
